[package]
name = "polarfire-softaes"
version = "0.1.0"
authors = ["Gui Andrade <gh@archshift.com>"]
edition = "2018"

[features]
default = []
sw = ["aes-ctr"]

[dependencies]
aes-ctr = {version = "0.6", optional = true}
bitutils = "3.0"
memmap = "0.7"
